---
# cPanel Git Deployment Configuration
# This file automates deployment when changes are pushed to the repository

deployment:
  tasks:
    # Set deployment path for nugui.co.za
    - export DEPLOYPATH=/home/nuguiyhv/public_html/
    
    # Create backup of current deployment
    - export BACKUPPATH=/home/nuguiyhv/backups/
    - mkdir -p $BACKUPPATH
    - export TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    - tar -czf $BACKUPPATH/backup_$TIMESTAMP.tar.gz $DEPLOYPATH --exclude=$DEPLOYPATH/writable --exclude=$DEPLOYPATH/vendor --exclude=$DEPLOYPATH/node_modules || true
    
    # Clear cache before deployment
    - rm -rf $DEPLOYPATH/writable/cache/* 2>/dev/null || true
    
    # Copy application files
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH 2>/dev/null || true
    - /bin/cp -R vendor $DEPLOYPATH 2>/dev/null || true
    
    # Copy public files
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH 2>/dev/null || true
    
    # Copy database folder
    - /bin/cp -R database $DEPLOYPATH 2>/dev/null || true
    
    # Copy configuration files
    - /bin/cp spark $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH 2>/dev/null || true
    - /bin/cp composer.lock $DEPLOYPATH 2>/dev/null || true
    - /bin/cp builds $DEPLOYPATH 2>/dev/null || true
    - /bin/cp preload.php $DEPLOYPATH 2>/dev/null || true
    - /bin/cp phpunit.xml.dist $DEPLOYPATH 2>/dev/null || true
    
    # Copy documentation (optional, can be removed if not needed)
    - /bin/cp -R docs $DEPLOYPATH 2>/dev/null || true
    - /bin/cp README.md $DEPLOYPATH 2>/dev/null || true
    - /bin/cp LICENSE $DEPLOYPATH 2>/dev/null || true
    - /bin/cp PROJECT_STRUCTURE.md $DEPLOYPATH 2>/dev/null || true
    
    # Copy essential files
    - /bin/cp robots.txt $DEPLOYPATH 2>/dev/null || true
    - /bin/cp favicon.ico $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
    
    # Copy environment file - use .env.production if .env doesn't exist
    - /bin/cp .env $DEPLOYPATH 2>/dev/null || /bin/cp .env.production $DEPLOYPATH/.env 2>/dev/null || true
    - /bin/cp env.production $DEPLOYPATH 2>/dev/null || true
    
    # Create writable directories if they don't exist
    - mkdir -p $DEPLOYPATH/writable/cache
    - mkdir -p $DEPLOYPATH/writable/logs
    - mkdir -p $DEPLOYPATH/writable/session
    - mkdir -p $DEPLOYPATH/writable/uploads
    - mkdir -p $DEPLOYPATH/writable/debugbar
    
    # Set proper permissions for writable directories
    - chmod -R 755 $DEPLOYPATH/writable
    - chmod -R 777 $DEPLOYPATH/writable/cache
    - chmod -R 777 $DEPLOYPATH/writable/logs
    - chmod -R 777 $DEPLOYPATH/writable/session
    - chmod -R 777 $DEPLOYPATH/writable/uploads
    - chmod -R 777 $DEPLOYPATH/writable/debugbar
    
    # Set proper permissions for security
    - chmod 644 $DEPLOYPATH/.env 2>/dev/null || true
    - chmod 755 $DEPLOYPATH/spark 2>/dev/null || true
    - chmod 644 $DEPLOYPATH/.htaccess 2>/dev/null || true
    
    # Clear CodeIgniter cache after deployment
    - cd $DEPLOYPATH && php spark cache:clear 2>/dev/null || true
    
    # Create deployment log
    - echo "Deployment completed at $(date)" >> $DEPLOYPATH/writable/logs/deployment.log
    - echo "Deployed from commit: $(git rev-parse HEAD)" >> $DEPLOYPATH/writable/logs/deployment.log