---
deployment:
  tasks:
    # Set deployment paths
    - export DEPLOYPATH=/home/nuguiyhv/public_html/
    - export APPPATH=/home/nuguiyhv/
    
    # Deploy public web files
    - /bin/cp -f ./public/index.php $DEPLOYPATH
    - /bin/cp -f ./public/.htaccess $DEPLOYPATH
    - /bin/rsync -a --delete ./public/assets/ $DEPLOYPATH/assets/
    - /bin/rsync -a --delete ./public/css/ $DEPLOYPATH/css/
    - /bin/rsync -a --delete ./public/js/ $DEPLOYPATH/js/
    - /bin/cp -f ./public/robots.txt $DEPLOYPATH || true
    - /bin/cp -f ./public/sitemap.xml $DEPLOYPATH || true
    - /bin/cp -f ./public/favicon.ico $DEPLOYPATH || true
    - /bin/cp -f ./public/sw.js $DEPLOYPATH || true
    
    # Deploy application files
    - /bin/rsync -a --delete ./app/ $APPPATH/app/
    - /bin/rsync -a --delete ./vendor/ $APPPATH/vendor/
    - /bin/rsync -a --delete ./system/ $APPPATH/system/ || true
    
    # Deploy writable directories with proper structure
    - /bin/mkdir -p $APPPATH/writable/cache
    - /bin/mkdir -p $APPPATH/writable/logs  
    - /bin/mkdir -p $APPPATH/writable/session
    - /bin/mkdir -p $APPPATH/writable/uploads
    - /bin/rsync -a ./writable/ $APPPATH/writable/ || true
    
    # Deploy configuration files
    - /bin/cp -f ./.env.production $APPPATH/.env 2>/dev/null || /bin/cp -f ./.env $APPPATH/.env
    - /bin/cp -f ./composer.json $APPPATH/
    - /bin/cp -f ./composer.lock $APPPATH/ || true
    
    # Deploy database migration files for ticket system
    - /bin/mkdir -p $APPPATH/database
    - /bin/cp -f ./database/ticketing_system.sql $APPPATH/database/ || true
    
    # Update index.php to point to correct paths
    - /bin/sed -i "s|require realpath(FCPATH . '../app/Config/Paths.php')|require realpath(FCPATH . '../app/Config/Paths.php')|g" $DEPLOYPATH/index.php
    
    # Set correct file permissions
    - /bin/find $APPPATH -type d -exec chmod 755 {} \;
    - /bin/find $APPPATH -type f -exec chmod 644 {} \;
    - /bin/chmod -R 775 $APPPATH/writable
    - /bin/chmod 644 $APPPATH/.env
    
    # Deploy deployment scripts
    - /bin/cp -f ./deploy-production.php $APPPATH/
    - /bin/cp -f ./post-deploy.sh $APPPATH/
    - /bin/chmod +x $APPPATH/post-deploy.sh
    
    # Ensure web server can write to necessary directories
    - /bin/chown -R nuguiyhv:nobody $APPPATH/writable || true
    - /bin/chown -R nuguiyhv:nobody $DEPLOYPATH || true
    
    # Run post-deployment setup
    - $APPPATH/post-deploy.sh || echo "Post-deploy script completed with warnings"
