---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nuguiyhv/public_html/
    - /bin/rsync -a --delete --exclude '.git' ./ $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
