---
deployment:
  tasks:
    # Set up paths
    - export REPOPATH=/home/nuguiyhv/repositories/nugui-website
    - export APPPATH=/home/nuguiyhv/ci_app
    - export PUBLICPATH=/home/nuguiyhv/public_html
    - export BACKUPPATH=/home/nuguiyhv/backups
    
    # Create backup
    - mkdir -p $BACKUPPATH
    - export TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    - if [ -d "$APPPATH" ]; then tar -czf $BACKUPPATH/backup_$TIMESTAMP.tar.gz $APPPATH $PUBLICPATH --exclude=$APPPATH/writable/cache --exclude=$APPPATH/writable/logs --exclude=$APPPATH/vendor || true; fi
    
    # Create secure directory structure
    - mkdir -p $APPPATH
    - mkdir -p $APPPATH/writable/cache
    - mkdir -p $APPPATH/writable/logs
    - mkdir -p $APPPATH/writable/session
    - mkdir -p $APPPATH/writable/uploads
    - mkdir -p $APPPATH/writable/debugbar
    
    # Deploy application files to secure location
    - /bin/cp -R $REPOPATH/app $APPPATH/
    - /bin/cp -R $REPOPATH/system $APPPATH/
    - /bin/cp -R $REPOPATH/database $APPPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/tests $APPPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/writable $APPPATH/ 2>/dev/null || true
    
    # Copy composer files
    - /bin/cp $REPOPATH/composer.json $APPPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/composer.lock $APPPATH/ 2>/dev/null || true
    
    # Copy other configuration files
    - /bin/cp $REPOPATH/spark $APPPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/preload.php $APPPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/phpunit.xml.dist $APPPATH/ 2>/dev/null || true
    
    # Copy environment file
    - if [ -f "$REPOPATH/.env.production" ]; then /bin/cp $REPOPATH/.env.production $APPPATH/.env; elif [ -f "$REPOPATH/env.production" ]; then /bin/cp $REPOPATH/env.production $APPPATH/.env; fi
    
    # Set permissions (using 775 for better security while maintaining write access)
    - chmod 600 $APPPATH/.env 2>/dev/null || true
    - chmod 755 $APPPATH/spark 2>/dev/null || true
    - chmod -R 755 $APPPATH/app
    - chmod -R 755 $APPPATH/system
    - chmod -R 775 $APPPATH/writable
    - chmod -R 775 $APPPATH/writable/cache
    - chmod -R 775 $APPPATH/writable/logs
    - chmod -R 775 $APPPATH/writable/session
    - chmod -R 775 $APPPATH/writable/uploads
    
    # Deploy public files
    - find $PUBLICPATH -mindepth 1 -name '.well-known' -prune -o -type f -exec rm -f {} + 2>/dev/null || true
    - find $PUBLICPATH -mindepth 1 -name '.well-known' -prune -o -type d -exec rm -rf {} + 2>/dev/null || true
    - /bin/cp -R $REPOPATH/public/assets $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/public/css $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/public/js $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/public/images $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/public/robots.txt $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/public/favicon.ico $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/public/.htaccess $PUBLICPATH/ 2>/dev/null || true
    
    # Create secure index.php
    - echo '<?php' > $PUBLICPATH/index.php
    - echo 'define("FCPATH", __DIR__ . DIRECTORY_SEPARATOR);' >> $PUBLICPATH/index.php
    - echo 'if (getcwd() . DIRECTORY_SEPARATOR !== FCPATH) { chdir(FCPATH); }' >> $PUBLICPATH/index.php
    - echo 'require "/home/nuguiyhv/ci_app/app/Config/Paths.php";' >> $PUBLICPATH/index.php
    - echo '$paths = new Config\Paths();' >> $PUBLICPATH/index.php
    - echo 'require "/home/nuguiyhv/ci_app/system/Boot.php";' >> $PUBLICPATH/index.php
    - echo 'require "/home/nuguiyhv/ci_app/app/Config/Boot/production.php";' >> $PUBLICPATH/index.php
    - echo 'exit(CodeIgniter\Boot::bootWeb($paths));' >> $PUBLICPATH/index.php
    
    # Update Paths.php
    - echo '<?php namespace Config;' > $APPPATH/app/Config/Paths.php
    - echo 'class Paths {' >> $APPPATH/app/Config/Paths.php
    - echo '  public string $systemDirectory = "/home/nuguiyhv/ci_app/system";' >> $APPPATH/app/Config/Paths.php
    - echo '  public string $appDirectory = "/home/nuguiyhv/ci_app/app";' >> $APPPATH/app/Config/Paths.php
    - echo '  public string $writableDirectory = "/home/nuguiyhv/ci_app/writable";' >> $APPPATH/app/Config/Paths.php
    - echo '  public string $testsDirectory = "/home/nuguiyhv/ci_app/tests";' >> $APPPATH/app/Config/Paths.php
    - echo '  public string $viewDirectory = "/home/nuguiyhv/ci_app/app/Views";' >> $APPPATH/app/Config/Paths.php
    - echo '}' >> $APPPATH/app/Config/Paths.php
    
    # Run post-deployment script if exists
    - if [ -f "$REPOPATH/.cpanel/post-deploy.sh" ]; then chmod +x $REPOPATH/.cpanel/post-deploy.sh && bash $REPOPATH/.cpanel/post-deploy.sh; fi
    
    # Clear cache
    - cd $APPPATH && php spark cache:clear 2>/dev/null || true
    
    # Success message
    - echo "Deployment completed successfully!"