---
# cPanel Git Deployment Configuration
# This file automates deployment when changes are pushed to the repository

deployment:
  tasks:
    # Set deployment path for nugui.co.za
    - export DEPLOYPATH=/home/nugui/public_html/
    
    # Create backup of current deployment (optional but recommended)
    - export BACKUPPATH=/home/nugui/backups/
    - mkdir -p $BACKUPPATH
    - export TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    - tar -czf $BACKUPPATH/backup_$TIMESTAMP.tar.gz $DEPLOYPATH --exclude=$DEPLOYPATH/writable --exclude=$DEPLOYPATH/vendor || true
    
    # Copy application files
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH 2>/dev/null || true
    
    # Copy system folder (required for CodeIgniter 4)
    - /bin/cp -R system $DEPLOYPATH 2>/dev/null || true
    
    # Copy configuration files
    - /bin/cp spark $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
    
    # Copy public/index.php to root (CodeIgniter 4 entry point)
    - /bin/cp public/index.php $DEPLOYPATH/index.php 2>/dev/null || true
    
    # Ensure assets are accessible
    - /bin/cp -R public/assets $DEPLOYPATH/assets 2>/dev/null || true
    - /bin/cp -R public/css $DEPLOYPATH/css 2>/dev/null || true
    - /bin/cp -R public/js $DEPLOYPATH/js 2>/dev/null || true
    - /bin/cp -R public/images $DEPLOYPATH/images 2>/dev/null || true
    
    # Create writable directories if they don't exist
    - mkdir -p $DEPLOYPATH/writable/cache
    - mkdir -p $DEPLOYPATH/writable/logs
    - mkdir -p $DEPLOYPATH/writable/session
    - mkdir -p $DEPLOYPATH/writable/uploads
    - mkdir -p $DEPLOYPATH/writable/debugbar
    
    # Set proper permissions for writable directories
    - chmod -R 755 $DEPLOYPATH/writable
    - chmod -R 777 $DEPLOYPATH/writable/cache
    - chmod -R 777 $DEPLOYPATH/writable/logs
    - chmod -R 777 $DEPLOYPATH/writable/session
    - chmod -R 777 $DEPLOYPATH/writable/uploads
    - chmod -R 777 $DEPLOYPATH/writable/debugbar
    
    # Copy environment file - use .env.production if .env doesn't exist
    - /bin/cp .env $DEPLOYPATH 2>/dev/null || /bin/cp .env.production $DEPLOYPATH/.env 2>/dev/null || true
    
    # Set proper permissions for security
    - chmod 644 $DEPLOYPATH/.env 2>/dev/null || true
    - chmod 755 $DEPLOYPATH/spark
    
    # Clear cache after deployment
    - cd $DEPLOYPATH && php spark cache:clear 2>/dev/null || true
    
    # Optional: Run database migrations (uncomment if using migrations)
    # - cd $DEPLOYPATH && php spark migrate 2>/dev/null || true
    
    # Optional: Install composer dependencies (uncomment if needed)
    # - cd $DEPLOYPATH && /usr/local/bin/composer install --no-dev --optimize-autoloader 2>/dev/null || true
    
    # Create deployment log
    - echo "Deployment completed at $(date)" >> $DEPLOYPATH/writable/logs/deployment.log