---
# Secure cPanel Git Deployment Configuration for CodeIgniter 4
# This deploys sensitive files OUTSIDE public_html for maximum security

deployment:
  tasks:
    # ============================================================
    # STEP 1: SET UP PATHS
    # ============================================================
    # Repository location (where cPanel clones the git repo)
    - export REPOPATH=/home/nuguiyhv/repositories/nugui-website
    
    # Secure application location (OUTSIDE public_html)
    - export APPPATH=/home/nuguiyhv/ci_app
    
    # Public web directory
    - export PUBLICPATH=/home/nuguiyhv/public_html
    
    # Backup location
    - export BACKUPPATH=/home/nuguiyhv/backups
    
    # ============================================================
    # STEP 2: CREATE BACKUP
    # ============================================================
    - mkdir -p $BACKUPPATH
    - export TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    - |
      if [ -d "$APPPATH" ]; then
        tar -czf $BACKUPPATH/backup_$TIMESTAMP.tar.gz $APPPATH $PUBLICPATH \
          --exclude=$APPPATH/writable/cache \
          --exclude=$APPPATH/writable/logs \
          --exclude=$APPPATH/vendor || true
        echo "Backup created: $BACKUPPATH/backup_$TIMESTAMP.tar.gz"
      fi
    
    # ============================================================
    # STEP 3: CREATE SECURE DIRECTORY STRUCTURE
    # ============================================================
    - mkdir -p $APPPATH
    - mkdir -p $APPPATH/writable/cache
    - mkdir -p $APPPATH/writable/logs  
    - mkdir -p $APPPATH/writable/session
    - mkdir -p $APPPATH/writable/uploads
    - mkdir -p $APPPATH/writable/debugbar
    
    # ============================================================
    # STEP 4: DEPLOY SENSITIVE FILES TO SECURE LOCATION
    # ============================================================
    # Copy application files (OUTSIDE public_html)
    - /bin/cp -R $REPOPATH/app $APPPATH/ || exit 1
    - /bin/cp -R $REPOPATH/system $APPPATH/ || exit 1
    - /bin/cp -R $REPOPATH/vendor $APPPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/database $APPPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/tests $APPPATH/ 2>/dev/null || true
    
    # Copy configuration files
    - /bin/cp $REPOPATH/spark $APPPATH/ || exit 1
    - /bin/cp $REPOPATH/composer.json $APPPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/composer.lock $APPPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/preload.php $APPPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/builds $APPPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/phpunit.xml.dist $APPPATH/ 2>/dev/null || true
    
    # Copy environment file (with proper security)
    - |
      if [ -f "$REPOPATH/.env.production" ]; then
        /bin/cp $REPOPATH/.env.production $APPPATH/.env
        echo "Copied .env.production to $APPPATH/.env"
      elif [ -f "$REPOPATH/env.production" ]; then
        /bin/cp $REPOPATH/env.production $APPPATH/.env
        echo "Copied env.production to $APPPATH/.env"
      fi
    
    # ============================================================
    # STEP 5: SECURE PERMISSIONS FOR SENSITIVE FILES
    # ============================================================
    - chmod 600 $APPPATH/.env 2>/dev/null || true
    - chmod 755 $APPPATH/spark
    - chmod -R 755 $APPPATH/app
    - chmod -R 755 $APPPATH/system
    - chmod -R 775 $APPPATH/writable
    - chmod -R 777 $APPPATH/writable/cache
    - chmod -R 777 $APPPATH/writable/logs
    - chmod -R 777 $APPPATH/writable/session
    - chmod -R 777 $APPPATH/writable/uploads
    
    # ============================================================
    # STEP 6: DEPLOY PUBLIC FILES ONLY TO public_html
    # ============================================================
    # Clear old public files (keep .well-known for SSL)
    - find $PUBLICPATH -mindepth 1 -name '.well-known' -prune -o -type f -exec rm -f {} + 2>/dev/null || true
    - find $PUBLICPATH -mindepth 1 -name '.well-known' -prune -o -type d -exec rm -rf {} + 2>/dev/null || true
    
    # Copy ONLY public assets
    - /bin/cp -R $REPOPATH/public/assets $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/public/css $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/public/js $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp -R $REPOPATH/public/images $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/public/robots.txt $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp $REPOPATH/public/favicon.ico $PUBLICPATH/ 2>/dev/null || true
    
    # ============================================================
    # STEP 7: CREATE SECURE index.php ENTRY POINT
    # ============================================================
    - |
      cat > $PUBLICPATH/index.php << 'EOF'
      <?php
      
      /**
       * CodeIgniter 4 - Secure Entry Point
       * This file loads the application from a secure location outside public_html
       */
      
      // Path to the front controller
      define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);
      
      // Ensure PHP version is compatible
      if (version_compare(PHP_VERSION, '7.4', '<')) {
          die('Your PHP version must be 7.4 or higher to run CodeIgniter 4. Current version: ' . PHP_VERSION);
      }
      
      // Path to the secure application folder (OUTSIDE public_html)
      $pathsConfig = '/home/nuguiyhv/ci_app/app/Config/Paths.php';
      
      // Check if application exists
      if (!file_exists($pathsConfig)) {
          header('HTTP/1.1 503 Service Unavailable.', TRUE, 503);
          die('The application is currently undergoing maintenance. Please try again later.');
      }
      
      // Load the paths config file
      require_once $pathsConfig;
      $paths = new Config\Paths();
      
      // Load our paths config file
      require '/home/nuguiyhv/ci_app/app/Config/Paths.php';
      $paths = new Config\Paths();
      
      // Location of the framework bootstrap file  
      require '/home/nuguiyhv/ci_app/app/Config/Boot/production.php';
      
      // Load Common.php for helper functions (needed for env() function)
      require '/home/nuguiyhv/ci_app/system/Common.php';
      
      // Load environment settings from .env files
      require_once '/home/nuguiyhv/ci_app/system/Config/DotEnv.php';
      (new CodeIgniter\Config\DotEnv('/home/nuguiyhv/ci_app'))->load();
      
      // Define ENVIRONMENT
      if (!defined('ENVIRONMENT')) {
          define('ENVIRONMENT', env('CI_ENVIRONMENT', 'production'));
      }
      
      // Boot the application
      require '/home/nuguiyhv/ci_app/system/CodeIgniter.php';
      EOF
    
    # ============================================================
    # STEP 8: CREATE SECURE .htaccess FILE
    # ============================================================
    - |
      cat > $PUBLICPATH/.htaccess << 'EOF'
      # Disable directory browsing
      Options All -Indexes
      
      # Disable server signature
      ServerSignature Off
      
      # Prevent access to hidden files
      <FilesMatch "^\.">
          Order allow,deny
          Deny from all
      </FilesMatch>
      
      # Prevent access to sensitive files
      <FilesMatch "\.(env|json|lock|yaml|yml|md|gitignore|gitattributes|ini|log|sql)$">
          Order allow,deny
          Deny from all
      </FilesMatch>
      
      # Force HTTPS
      RewriteEngine On
      RewriteCond %{HTTPS} off
      RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
      
      # Remove www
      RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]
      RewriteRule ^(.*)$ https://%1/$1 [R=301,L]
      
      # CodeIgniter 4 routing
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule ^([\s\S]*)$ index.php/$1 [L,NC,QSA]
      
      # Security headers
      <IfModule mod_headers.c>
          Header set X-Content-Type-Options "nosniff"
          Header set X-Frame-Options "SAMEORIGIN"
          Header set X-XSS-Protection "1; mode=block"
          Header set Referrer-Policy "strict-origin-when-cross-origin"
          Header set Strict-Transport-Security "max-age=31536000; includeSubDomains"
          Header always unset "X-Powered-By"
      </IfModule>
      
      # Block access to sensitive paths (if accidentally exposed)
      RedirectMatch 404 /\.git
      RedirectMatch 404 /vendor/.*$
      RedirectMatch 404 /system/.*$
      RedirectMatch 404 /app/.*$
      RedirectMatch 404 /writable/.*$
      RedirectMatch 404 /tests/.*$
      RedirectMatch 404 /database/.*$
      RedirectMatch 404 /docs/.*$
      RedirectMatch 404 /dev-tools/.*$
      
      # Compress text files
      <IfModule mod_deflate.c>
          AddOutputFilterByType DEFLATE text/plain
          AddOutputFilterByType DEFLATE text/html
          AddOutputFilterByType DEFLATE text/xml
          AddOutputFilterByType DEFLATE text/css
          AddOutputFilterByType DEFLATE application/xml
          AddOutputFilterByType DEFLATE application/xhtml+xml
          AddOutputFilterByType DEFLATE application/rss+xml
          AddOutputFilterByType DEFLATE application/javascript
          AddOutputFilterByType DEFLATE application/x-javascript
      </IfModule>
      EOF
    
    # ============================================================
    # STEP 9: UPDATE PATHS.PHP FOR SECURE STRUCTURE
    # ============================================================
    - |
      cat > $APPPATH/app/Config/Paths.php << 'EOF'
      <?php
      
      namespace Config;
      
      /**
       * Paths Configuration for Secure Deployment
       * All paths point to locations OUTSIDE public_html for security
       */
      class Paths
      {
          // System directory
          public string $systemDirectory = '/home/nuguiyhv/ci_app/system';
          
          // Application directory
          public string $appDirectory = '/home/nuguiyhv/ci_app/app';
          
          // Writable directory for logs, cache, etc.
          public string $writableDirectory = '/home/nuguiyhv/ci_app/writable';
          
          // Tests directory
          public string $testsDirectory = '/home/nuguiyhv/ci_app/tests';
          
          // View directory
          public string $viewDirectory = '/home/nuguiyhv/ci_app/app/Views';
      }
      EOF
    
    # ============================================================
    # STEP 10: CLEAR CACHE AND LOG DEPLOYMENT
    # ============================================================
    - cd $APPPATH && php spark cache:clear 2>/dev/null || true
    
    # Create deployment log
    - |
      echo "========================================" >> $APPPATH/writable/logs/deployment.log
      echo "Deployment completed at: $(date)" >> $APPPATH/writable/logs/deployment.log
      echo "Deployed from commit: $(cd $REPOPATH && git rev-parse HEAD)" >> $APPPATH/writable/logs/deployment.log
      echo "Repository branch: $(cd $REPOPATH && git branch --show-current)" >> $APPPATH/writable/logs/deployment.log
      echo "Secure paths configured:" >> $APPPATH/writable/logs/deployment.log
      echo "  - App: $APPPATH" >> $APPPATH/writable/logs/deployment.log
      echo "  - Public: $PUBLICPATH" >> $APPPATH/writable/logs/deployment.log
      echo "========================================" >> $APPPATH/writable/logs/deployment.log
    
    # Final success message
    - echo "✅ Secure deployment completed successfully!"